/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main_Project;

import java.awt.Color;

/**
 *
 * @author nick.schroeder
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        btn2 = new javax.swing.JButton();
        start = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        win = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        delete = new javax.swing.JRadioButtonMenuItem();
        mode = new javax.swing.JMenu();
        player1 = new javax.swing.JRadioButtonMenuItem();
        player2 = new javax.swing.JRadioButtonMenuItem();
        difficulty = new javax.swing.JMenu();
        normal_mode = new javax.swing.JRadioButtonMenuItem();
        insanity_mode = new javax.swing.JRadioButtonMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btn2.setText(" ");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        btn3.setText(" ");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn1.setText(" ");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn5.setText(" ");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText(" ");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setText(" ");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setText(" ");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText(" ");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText(" ");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        menu.setText("Menu");
        menu.setActionCommand("menu");

        delete.setText("Exit");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        menu.add(delete);

        jMenuBar1.add(menu);

        mode.setText("Mode");

        player1.setText("1 Player vs. CPU (WIP)");
        player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ActionPerformed(evt);
            }
        });
        mode.add(player1);

        player2.setSelected(true);
        player2.setText("2 Players");
        player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ActionPerformed(evt);
            }
        });
        mode.add(player2);

        jMenuBar1.add(mode);

        difficulty.setText("Difficulty");

        normal_mode.setSelected(true);
        normal_mode.setText("Normal");
        normal_mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normal_modeActionPerformed(evt);
            }
        });
        difficulty.add(normal_mode);

        insanity_mode.setText("Insanity (WIP)");
        insanity_mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insanity_modeActionPerformed(evt);
            }
        });
        difficulty.add(insanity_mode);

        jMenuBar1.add(difficulty);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(win, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(win, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(start)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int p1 = 1;
    int p2 = 0;
    int b1 = -1;
    int b2 = -1;
    int b3 = -1;
    int b4 = -1;
    int b5 = -1;
    int b6 = -1;
    int b7 = -1;
    int b8 = -1;
    int b9 = -1;
    int winner = 0;
    int insanity = 0;

    void win_check() {
        if (b5 != 0) {
            if (btn5.getText().equals(btn1.getText()) && btn5.getText().equals(btn9.getText())) {
                btn1.setBackground(Color.green);
                btn5.setBackground(Color.green);
                btn9.setBackground(Color.green);
                if (btn5.getText().equals("X")) {
                    winner = 1;
                } else {
                    winner = 2;
                }
            } else if (btn5.getText().equals(btn2.getText()) && btn5.getText().equals(btn8.getText())) {
                btn2.setBackground(Color.green);
                btn5.setBackground(Color.green);
                btn8.setBackground(Color.green);
                if (btn5.getText().equals("X")) {
                    winner = 1;
                } else {
                    winner = 2;
                }
            } else if (btn5.getText().equals(btn3.getText()) && btn5.getText().equals(btn7.getText())) {
                btn3.setBackground(Color.green);
                btn5.setBackground(Color.green);
                btn7.setBackground(Color.green);
                if (btn5.getText().equals("X")) {
                    winner = 1;
                } else {
                    winner = 2;
                }
            } else if (btn5.getText().equals(btn4.getText()) && btn5.getText().equals(btn6.getText())) {
                btn4.setBackground(Color.green);
                btn5.setBackground(Color.green);
                btn6.setBackground(Color.green);
                if (btn5.getText().equals("X")) {
                    winner = 1;
                } else {
                    winner = 2;
                }
            }
        }
        if (winner == 0) {
            if (b1 != 0) {
                if (btn1.getText().equals(btn2.getText()) && btn1.getText().equals(btn3.getText())) {
                    btn1.setBackground(Color.green);
                    btn2.setBackground(Color.green);
                    btn3.setBackground(Color.green);
                    if (btn5.getText().equals("X")) {
                        winner = 1;
                    } else {
                        winner = 2;
                    }
                } else if (btn1.getText().equals(btn4.getText()) && btn1.getText().equals(btn7.getText())) {
                    btn1.setBackground(Color.green);
                    btn4.setBackground(Color.green);
                    btn7.setBackground(Color.green);
                    if (btn5.getText().equals("X")) {
                        winner = 1;
                    } else {
                        winner = 2;
                    }
                }
            }
        }
        if (winner == 0) {
            if (b9 != 0) {
                if (btn9.getText().equals(btn6.getText()) && btn9.getText().equals(btn3.getText())) {
                    btn3.setBackground(Color.green);
                    btn6.setBackground(Color.green);
                    btn9.setBackground(Color.green);
                    if (btn5.getText().equals("X")) {
                        winner = 1;
                    } else {
                        winner = 2;
                    }
                } else if (btn9.getText().equals(btn8.getText()) && btn9.getText().equals(btn7.getText())) {
                    btn7.setBackground(Color.green);
                    btn8.setBackground(Color.green);
                    btn9.setBackground(Color.green);
                    if (btn5.getText().equals("X")) {
                        winner = 1;
                    } else {
                        winner = 2;
                    }
                }
            }
        }
        if (winner != 0) {
            this.win.setText("The Winner is Player: " + winner);
            b1 = -2;
            b2 = -2;
            b3 = -2;
            b4 = -2;
            b5 = -2;
            b6 = -2;
            b7 = -2;
            b8 = -2;
            b9 = -2;
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (p1 == 1) {
            this.btn1.setText("X");
            p1 = 0;
            p2 = 1;
            b1 = 1;
        } else if (p2 == 1) {
            this.btn1.setText("O");
            p1 = 1;
            p2 = 0;
            b1 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn1.setEnabled(false);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (p1 == 1) {
            this.btn2.setText("X");
            p1 = 0;
            p2 = 1;
            b2 = 1;
        } else if (p2 == 1) {
            this.btn2.setText("O");
            p1 = 1;
            p2 = 0;
            b2 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn2.setEnabled(false);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (p1 == 1) {
            this.btn3.setText("X");
            p1 = 0;
            p2 = 1;
            b3 = 1;
        } else if (p2 == 1) {
            this.btn3.setText("O");
            p1 = 1;
            p2 = 0;
            b3 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn3.setEnabled(false);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (p1 == 1) {
            this.btn4.setText("X");
            p1 = 0;
            p2 = 1;
            b4 = 1;
        } else if (p2 == 1) {
            this.btn4.setText("O");
            p1 = 1;
            p2 = 0;
            b4 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn4.setEnabled(false);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (p1 == 1) {
            this.btn5.setText("X");
            p1 = 0;
            p2 = 1;
            b5 = 1;
        } else if (p2 == 1) {
            this.btn5.setText("O");
            p1 = 1;
            p2 = 0;
            b5 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn5.setEnabled(false);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (p1 == 1) {
            this.btn6.setText("X");
            p1 = 0;
            p2 = 1;
            b6 = 1;
        } else if (p2 == 1) {
            this.btn6.setText("O");
            p1 = 1;
            p2 = 0;
            b6 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn6.setEnabled(false);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (p1 == 1) {
            this.btn7.setText("X");
            p1 = 0;
            p2 = 1;
            b7 = 1;
        } else if (p2 == 1) {
            this.btn7.setText("O");
            p1 = 1;
            p2 = 0;
            b7 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn7.setEnabled(false);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (p1 == 1) {
            this.btn8.setText("X");
            p1 = 0;
            p2 = 1;
            b8 = 1;
        } else if (p2 == 1) {
            this.btn8.setText("O");
            p1 = 1;
            p2 = 0;
            b8 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn8.setEnabled(false);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (p1 == 1) {
            this.btn9.setText("X");
            p1 = 0;
            p2 = 1;
            b9 = 1;
        } else if (p2 == 1) {
            this.btn9.setText("O");
            p1 = 1;
            p2 = 0;
            b9 = 2;
        }
        win_check();
        if (insanity == 0) {
            btn9.setEnabled(false);
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        p1 = 1;
        p2 = 0;
        b1 = 0;
        b2 = 0;
        b3 = 0;
        b4 = 0;
        b5 = 0;
        b6 = 0;
        b7 = 0;
        b8 = 0;
        b9 = 0;
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn1.setText(" ");
        btn2.setText(" ");
        btn3.setText(" ");
        btn4.setText(" ");
        btn5.setText(" ");
        btn6.setText(" ");
        btn7.setText(" ");
        btn8.setText(" ");
        btn9.setText(" ");
        btn1.setBackground(Color.WHITE);
        btn2.setBackground(Color.WHITE);
        btn3.setBackground(Color.WHITE);
        btn4.setBackground(Color.WHITE);
        btn5.setBackground(Color.WHITE);
        btn6.setBackground(Color.WHITE);
        btn7.setBackground(Color.WHITE);
        btn8.setBackground(Color.WHITE);
        btn9.setBackground(Color.WHITE);
        win.setText(" ");
        start.setText("Restart");
        winner = 0;
        insanity = 0;
    }//GEN-LAST:event_startActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        dispose();
    }//GEN-LAST:event_deleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void insanity_modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insanity_modeActionPerformed
        insanity = 1;
        insanity_mode.setSelected(false);
    }//GEN-LAST:event_insanity_modeActionPerformed

    private void normal_modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normal_modeActionPerformed
        insanity = 0;
        normal_mode.setSelected(true);
    }//GEN-LAST:event_normal_modeActionPerformed

    private void player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1ActionPerformed
        player1.setSelected(false);
    }//GEN-LAST:event_player1ActionPerformed

    private void player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ActionPerformed
        player2.setSelected(true);
    }//GEN-LAST:event_player2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JRadioButtonMenuItem delete;
    private javax.swing.JMenu difficulty;
    private javax.swing.JRadioButtonMenuItem insanity_mode;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu mode;
    private javax.swing.JRadioButtonMenuItem normal_mode;
    private javax.swing.JRadioButtonMenuItem player1;
    private javax.swing.JRadioButtonMenuItem player2;
    private javax.swing.JButton start;
    private javax.swing.JLabel win;
    // End of variables declaration//GEN-END:variables
}
